from algorithm_study.heap.max_heap import MaxHeap
from algorithm_study.heap.max_heap_item import MaxHeapItem
from algorithm_study.functions.generate_random_number import generate_random_number


def main():
    max_heap = MaxHeap()

    (
        max_heap
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 1', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 2', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 3', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 4', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 5', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 6', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 7', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 8', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 9', str(item)))
        .insert(MaxHeapItem[float, str](generate_random_number(), f'test{generate_random_number()}'))
        .for_each(lambda item: print('insert 10', str(item)))
        .remove(lambda item: print('----- remove 1', str(item)))
        # .for_each(lambda item: print('remove 1', str(item)))
        .remove(lambda item: print('----- remove 2', str(item)))
        # .for_each(lambda item: print('remove 2', str(item)))
        .remove(lambda item: print('----- remove 3', str(item)))
        # .for_each(lambda item: print('remove 3', str(item)))
        .remove(lambda item: print('----- remove 4', str(item)))
        # .for_each(lambda item: print('remove 4', str(item)))
        .remove(lambda item: print('----- remove 5', str(item)))
        # .for_each(lambda item: print('remove 5', str(item)))
        .remove(lambda item: print('----- remove 6', str(item)))
        # .for_each(lambda item: print('remove 6', str(item)))
        .remove(lambda item: print('----- remove 7', str(item)))
        # .for_each(lambda item: print('remove 7', str(item)))
        .remove(lambda item: print('----- remove 8', str(item)))
        # .for_each(lambda item: print('remove 8', str(item)))
        .remove(lambda item: print('----- remove 9', str(item)))
        # .for_each(lambda item: print('remove 9', str(item)))
        .remove(lambda item: print('----- remove 10', str(item)))
        # .for_each(lambda item: print('remove 10', str(item)))
    )
